#!/usr/bin/env python3
"""Generate ET1 qpos visualizer HTML from the latest deployment CSV dump."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EXPORTER = Path(
    "/home/galbot/galbot_rl_mjlab/src/mjlab/scripts/export_dds_real_qpos_visualizer.py"
)
DEFAULT_CSV_GLOB = (
    PROJECT_ROOT
    / "deploy/robots/et1/debug/qpos_visualizer/general_tracker_cln_qpos_visualizer_*.csv"
)
DEFAULT_JOINT_XML = PROJECT_ROOT / "deploy/robots/et1/galbot_ET1_0423_26_sdk_collision.xml"
DEFAULT_OUTPUT = (
    PROJECT_ROOT
    / "deploy/robots/et1/debug/qpos_visualizer/general_tracker_cln_qpos_visualizer-cjm.html"
)


def latest_csv(pattern: Path) -> Path:
    matches = sorted(pattern.parent.glob(pattern.name), key=lambda path: path.stat().st_mtime)
    if not matches:
        raise FileNotFoundError(f"No qpos visualizer CSV matched: {pattern}")
    return matches[-1]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", type=Path, default=None, help="CSV generated by et1_ctrl qpos visualizer dump.")
    parser.add_argument("--csv-glob", type=Path, default=DEFAULT_CSV_GLOB)
    parser.add_argument("--exporter", type=Path, default=DEFAULT_EXPORTER)
    parser.add_argument("--joint-xml", type=Path, default=DEFAULT_JOINT_XML)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--start-sec", type=float, default=0.0)
    parser.add_argument("--duration-sec", type=float, default=0.0, help="0 means full available duration.")
    parser.add_argument("--max-points", type=int, default=5500)
    args = parser.parse_args()

    csv_path = args.csv if args.csv is not None else latest_csv(args.csv_glob)
    if not csv_path.exists():
        raise FileNotFoundError(csv_path)
    if not args.exporter.exists():
        raise FileNotFoundError(args.exporter)

    cmd = [
        sys.executable,
        str(args.exporter),
        "--dds-csv",
        str(csv_path),
        "--joint-xml",
        str(args.joint_xml),
        "--output",
        str(args.output),
        "--start-sec",
        str(args.start_sec),
        "--max-points",
        str(args.max_points),
    ]
    if args.duration_sec > 0.0:
        cmd.extend(["--duration-sec", str(args.duration_sec)])
    else:
        cmd.extend(["--duration-sec", "1000000"])

    print(f"[export_qpos_visualizer_html] csv: {csv_path}")
    print(f"[export_qpos_visualizer_html] output: {args.output}")
    subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
